development:
  adapter: postgresql
  database: planting_season_api_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: planting_season_api_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: planting_season_api_production
  pool: 5
  timeout: 5000
  host: localhost
  username: plantingseason
  password: 'weema'
